#+title: Am I doing this Write?: A poignant chapbook collection of lyrical poems that explores love, loss, hidden struggles, and the lingering echoes of memories as well as the roads we wander.
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Am I doing this Write?: A poignant chapbook collection of lyrical poems that explores love, loss, hidden struggles, and the lingering echoes of memories as well as the roads we wander. --- Dwain Bachmann

** Rating

3.5/5 ★★★½☆

** Review

Thank you NetGalley and BooksGoSocial for sending this book for review consideration. All opinions are my own.

This to me was an okay selection of poetry. There were some really lovely poems and I hope "Reflections" stays with me for a long time.

However, it felt too simplistic. I personally prefer poems with a lot of imagery or beautiful phrases that feel beautiful to say. This didn't really have much of either for me. A lot of the poems just spell out what the author is feeling to meter or rhyme. Although this does help with accessibility I'd argue that some ambiguity is what makes poetry personal.

There was definitely more good than bad but it lacked something special to reach the 4 star mark.

** Tags

No tags.


** Links

