#+title: A Short History of Tractors in Ukrainian
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* A Short History of Tractors in Ukrainian --- Marina Lewycka

** Rating

3.0/5 ★★★☆☆

** Review

Fortunately for me this book was not in Ukrainian. Unfortunately it did not talk about tractors nearly as much as I would have wanted.

Beautifully written; I instantly felt immersed in the culture, lives and history of the characters.

The tone of the story was just right, light and witty when it suited but harsh and emotive when needed. I loved the parallels and foreshadowing in the tractor sections.

The ending was somewhat predictable but that's not what the book is about. For me, the conclusion could have focused more on the perspective of the antagonist's back story as I felt the back story that was covered in the penultimate chapter was redundant due a lot of the information already being known.

The main thing that prevented a higher star rating was the characters. Although well written and well presented, they will not stay with me, with the possible exception of Nikolai. This almost feels like a judge of character, insomuch as that the people that characters are drawn from are of no interest to me but that is the sad truth. Maybe that's the point and if so, the author can take solace in the fact that my lack of full marks is due to shortcomings in literary intelligence. The end result is the same. 3 stars.

** Links

