#+title: Behind the Sequins: My Life
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Behind the Sequins: My Life --- Shirley Ballas

** Rating

4.5/5 ★★★★½

** Review

I started this book and, after finishing the first chapter, I was thinking this would be a 3 maybe 3.5 star read at a push. My main problem is I wanted to be more raw, it felt like a lot of the emotions were just surface level.

Well, Shirley delivered in the rest of book! Reflective, honest and raw whilst staying true to herself. The dancing aspects were of course interesting and Shirley's phenomenal success in the dancing world is an interesting read. 

For me, however, it was the family life (in particular her brother and mother) that had me balling my eyes out. Shirley did not seem to be an old head on young shoulders and seems to have learnt many life lessons through personal experience. I appreciate how difficult this must have been to write and I want to thank Shirley for allowing people to look behind the sequins and see the real her.

** Links

