#+title: Be Useful
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Be Useful --- Arnold Schwarzenegger

** Rating

1.0/5 ★☆☆☆☆

** Review

Unoriginal and Potentially Harmful

This book is essentially Arnold bragging about his achievements whilst peddling unoriginal, capitalist and hyper-masculine motivational advice.

The book started off well and the parts about Arnold's life were interesting. I did also pick up the odd bit of advice - hence the star. However, if you've read any other self-help or motivational book before this will bring little new to the table. This book is also way too long and could essentially be condensed into a long blog post.

All the time Arnold was bragging about his success and spouting motivational dogma, I was reminded of the Joseph Heller quote, often paraphrased as:

 "I have something he will never have – enough."

Arnold has clearly a very narrow view of success similar to those of Donald Trump, Elon Musk and Jeff Bezos. That is, success is focused on wealth, fame, status and other shallow capitalist based ideals. This idea of success can never achieve contentment and fosters unhappiness, jealously and resentment.

Some advice was generic enough to be applicable outside this egoistical world view but lots could be very damaging to those around you and the ones you love. The idea that you have to sell ideas to your significant other and, even if they say "No" to such things as emigrating, that doesn't need to stop you, is down right inconsiderate. There's even the advice to "hit the brakes a little less" to get more hours in the day by saving time in your commute.

Another thing that stood out for me is that Arnold doesn't acknowledge his own privileges (gender, race, sexual orientation, ablist, etc.) or that his "success" was based off the back of his body building career which wouldn't have existed if it weren't for steroid usage.

A lot of his "inspirational" merely highlighted that Arnold is unaware of survival bias which explains his warped view of risk.

It will come as no surprise that I do not recommend this book and 1 star was a generous rating. If you're interested in reading in this area, I would recommend reading Zen Mind, Beginners Mind or Getting things Done and staying away from this warped, outdated and macho piece of capitalist propaganda.

** Tags

No tags.


** Links

