#+title: Babel
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 23:11:04 GMT
#+filetags: :book-review:

* Babel --- R. F. Kuang

** Rating

3.5/5 ★★★½☆

** Review

I'm so conflicted with how to rate this book because I can't really figure out what it was meant to be.

The magic system felt superficially integrated into the world (more on a symbolic level) which meant it felt more like alt-history than fantasy. Yet you don't get those moments that make you question the chaos of reality like you do with alt-history nor do you get fantastical world building like you do with fantasy.

The themes are incredibly serious that need to be handled carefully and respectfully but the main story seemed too clichéd for the themes to be taken as seriously as they deserved. Moreover, it didn't seem like this book brought anything new to the table about the atrocities of colonialism, sexism and racism. Rather it had quite a simple rhetoric that it repeated over and over with little development. This repetition didn't leave much room to discuss the intersection with other themes such as religion.

By primarily being a single POV narrative the book innately limited the suspense and world building potential. And the key events that happened to each character, along with ending, seemed very predictable.

So I'm left with the impression that this book did a sub-par job at a lot of different areas because it couldn't decide what it was. At the beginning of the book I was sure this was going to be a 5 star read for me and the fact that it isn't highlights the overly ambitious and ultimately underdeveloped nature of the book.

With that being said, it was beautifully written and I will likely read more of RF Kaung's work.

** Links

- [[https://fable.co/book/babel-by-r-f-kuang-9780063021440][View on Fable]]
