#+title: Dear Reader
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Dear Reader --- Cathy Rentzenbrink

** Rating

4.0/5 ★★★★☆

** Review

A lovely autobiographical piece told through a love of books. A few reviews said this was nothing special or very middle of the road. I disagree and particularly like the humanism and honesty the author lays down for the reader.

The reason for the book losing a star is that I feel like more authors from minority backgrounds could have been mentioned in the recommendations. Additionally, Harry Potter was celebrated which lost marks for me. Although this book was published in 2020, as far as I'm aware it was known that JK Rowling was transphobic at this point and so I don't feel like the celebration of her work can be justified.

That aside, the biography was beautiful but I'd take the reading recommendations with a pinch of salald*.

*I mistyped and my phone autocorrected salt to salad. I'm now coining that as a phrase to mean something is lacking ethnic and gender diversity.

** Tags

No tags.


** Links

