#+title: Dungeon Crawler Carl
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 23:11:04 GMT
#+filetags: :book-review:

* Dungeon Crawler Carl --- Matt Dinniman

** Rating

5.0/5 ★★★★★

** Review

By about 50 pages in, I knew that this was going to be one of my favourite series. Think of this series like the baby of Rick & Morty and the Elder Scrolls, raised by The Boys and The Hitchhicker's Guide to the Universe.

It has me genuinely laughing out load whilst minutes latter thinking hard about the morality of the world we live in.

I was genuinely addicted to this book. The closest feeling I've experienced to this was when I was a teen playing the Elder Scrolls series, I was just captivated by the world and story, and  instantly became fully immersed. The times I wasn't reading I was counting down the hours until I could read this again.

I could not rate this book high enough to those who enjoy fantasy, humour, RPG and epic world building.

** Links

- [[https://fable.co/book/dungeon-crawler-carl-by-matt-dinniman-978059][View on Fable]]
