#+title: Howl, Kaddish and Other Poems
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Howl, Kaddish and Other Poems --- Allen Ginsberg

** Rating

5.0/5 ★★★★★

** Review

This is my first time reading any of Allen Ginsberg's work and most certainly won't be my last.

I can't really describe what I've just experienced but I loved it. It felt like some has grabbed my eyeballs and pulled my brain through some psychedelic trance where everything is simultaneously obvious and incomprehensible. The closest experience I've had to this is when I first listened to Miles Davis' album "Bitches Brew".

Additionally, I cannot actually believe poems like these were written in 50s. It feels like so much of Allen's fears are relevant today more than ever. Moreover so much of his writing feels like a perfect description of our current dystopian technology.

I'm still processing what I've just read but this is the best attempt at a review my brain can yield.

** Tags

No tags.


** Links

