#+title: Hyperion
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Hyperion --- Dan Simmons

** Rating

5.0/5 ★★★★★

** Review

I can say with confidence that this is the best book I've read this year and will be at the end of the year. Given the quality of the books I've read so far, this is rightly a significant accolade.

The plot is phenomenal, truly awesome in scope, detail and execution. The characters are so raw, real and memorable. All will stay with me for decades to come. The worlds were meticulously imagined. The writing is just beautiful. This is a book for anyone who appreciates mastery of the writing craft - even if they despise fantasy and sci-fi.

With all that aside, what Dan Simmons did best was have my emotions and mind like putty in his hand. I genuinely laughed out load, experienced tears of joy and fits of rage all before doing some mental gymnastics and then quietly pondering the morality of existence. My mind did what Dan Simmons wanted it to do.

I cannot recommend this book enough. I'm itching to read the second book right now but I know that I will never get another chance to read it for the first time again so I am going to savour each and every installment in the Hyperion Cantos.

** Links

