#+title: It Happened One Summer
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* It Happened One Summer --- Tessa Bailey

** Rating

4.0/5 ★★★★☆

** Review

Trying to write this review through the water in my eyes. Due to the smoke. From the FIRE IN MY LOINS! This book was some sexy escapism and also made me want to become a fisherman.

The characters were more fleshed out than I would have expected and their growth felt believable and timely. There were several moments where I felt an aspect was missing and then I'm reading the missing piece moments later.

The main draw backs for me were the lack of body positivity (normal people can fall in love and have good sex too) and the lack of depth to the secondary cast. I know Hannah and Fox get their own book but this book could have easily benefited from more fleshed out side characters. Additionaly some plot lines felt unnecessary but I feel like the book embraces the clichéd cheesy elements.

Won't be my last romance book.

** Tags

No tags.


** Links

