#+title: Iron Flame
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Iron Flame --- Rebecca Yarros

** Rating

2.5/5 ★★½☆☆

** Review

This was quite a difficult book to review. It took me some time (as with the last book) to remember that this is not a fantasy book but rather a romantasy. That is, I had to try and ignore all of the holes in the world building - portable clocks with second precision, Julian calendar, mass produced shoes with standard sizing, etc.*

That aside, what this book gets right is pace. It's very fast passed, short chapters and most chapters end on a cliff hanger. A very easy read indeed.

The plot was also interesting, I didn't like the ending but that aside I enjoyed the rest of the book's plot.

I really struggled with Violet and Xaden's relationship. Not only did they have same fight thoughout the book but I actually don't think they're a great match. The relationship seems to bring out the worst in each other and the emotional relationship reads like one between two mid teens. Not something between two people in their mid twenties.

Another thing I struggled with was the 1 dimensional characters. It's only in the last 100 pages that the side characters start to get some depth and that's after reading about 1000 pages in this story. The main characters seem very tropey and lack any emotional depths.

Overall I feel like I would potentially read  other books by Yarros but unlikely in fantasy world unless forced. The lack of depth in the world, 1 dimensional characters and shallow relationships left the book only being carried by it's pace and semi-decent plot.

* As an aside, General Melgren's ability to predict the outcome of future battles negates free will. Perfectly fine and wouldn't change the story but I doubt this will ever be explore in the series. More of a side effect of the magic system being if Yarros thinks of it, it can happen.

** Links

