#+title: Jurassic Park
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Jurassic Park --- Michael Crichton

** Rating

4.0/5 ★★★★☆

** Review

The perfect realisation for this idea sits somewhere between the book and film - but a lot closer to the latter.
This book had every potential to be a solid 5 stars but, if I'm truly honest, it only attained 4 stars because of my love for dinosaurs.

The biggest difficulty was the apparent short-term memory of the characters who are being chased by a T-rex one minute and then next are going about their life as if nothing has happened? The 8 year old girl seems completely unphased by a 7 tonne prehistoric killing machine and proceeds to whine about dinner when the monster is out of ear shot. Most of the characters only seemed to remember they were in the middle of a life threatening disaster when a dinosaur was standing in front of them.

Additionally, Malcolm's monologues got tiring. What started off as genuine critiques of the scientific process quickly descended into something that resembled bitching about an ex. I'm wondering if the author wanted a career in science but got turned down and so let out his teenage angst-like frustration through the voice of Malcolm. Similarly the thinly veiled monologue about humans not having the power to alter the climate in a book about bringing dinosaurs back to life seemed a little ironic.

That said, this book does just hit right with the political ramifications, unwieldy nature of the progress, tension, dinosaurs and the detailing of the parks computer system.

Ultimately, I think that's why the film was such a success. They dropped the political backdrop along with some of the finer details of the world but crucially ditched Malcolm's monologues and the actors actually responded to terrifying situations with terror.

Even though this was a 4 star review I'm gutted - as, for me, this could have been one of my favourite books but it was let down by it's execution.

** Tags

No tags.


** Links

- [[https://fable.co/book/jurassic-park-by-michael-crichton][View on Fable]]
