#+title: Mistborn
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Mistborn --- Brandon Sanderson

** Rating

4.5/5 ★★★★½

** Review

This books is Michaelangelo's David had Michaelangelo finished a couple weeks early and called it a day. There is the potential to be something truly brilliant but the finishing touches just weren't there.

Lots of little things from talking about plot critical secrets whilst incognito in a room full of enemies whereby some likely have supernatural hearing; to having a videogame style tutorial to introduce the magic system.

The two main letdowns for me were the magic system and the characters. Both of which felt underdeveloped. The characters were clichéd. More depth than what I'd call a 1D character but still very cheesy. The magic system felt like elements were simplified so that it would play well as a videogame. I have an understanding when playing a videogame that some elements have to be simplified to make the game playable but in a book!? The world is your oyster! For me, it didn't feel believable/immersive and with the magic system being so integral to this book I found lots of sections quite jarring.

With all that being said, the pacing of the end of the book was fantastic - albeit with a predictable plot. I finished the last quarter at breakneck speed as I was hooked. The overall plot is engaging and no part ever felt like a drag. I'll definitely finish the series and hopefully I'll enjoy future books more as the magic system won't have to be re-explained and the characters start to flesh out.

** Tags

No tags.


** Links

