#+title: Pawn of Prophecy (The Belgariad, #1)
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 23:11:04 GMT
#+filetags: :book-review:

* Pawn of Prophecy (The Belgariad, #1) --- David Eddings

** Rating

3.5/5 ★★★½☆

** Review

I'm aware that this book is a starter. Something to wet my appetite for the Belgariad series without filling my hunger. Nonetheless, it felt lacking. It smelled lovely but as I started to tuck in, I realised that the ingredients weren't anything special and the whole dish has been undercooked.

Its clichéd but with not enough substance elsewhere to make up for that. It's like one of those romcoms that netflix churns out year after year. Nothing special but something to watch in that genre. I very much doubt I'll pick up the rest of the series but it wouldn't be the end of the world.

I have no doubt of the historical significance of the book but compared to the other book from same decade that I'm reading (Hyperion) it's pales into insignificance.

** Links

