#+title: 東京喰種トーキョーグール:re 1 [Tokyo Guru:re 1] (Tokyo Ghoul:re, #1)
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* 東京喰種トーキョーグール:re 1 [Tokyo Guru:re 1] (Tokyo Ghoul:re, #1) --- Sui Ishida

** Rating

3.5/5 ★★★½☆

** Review

Anyone who has ever read any manga before and is currently deciding whether to read this or not, ignore this review. I don't know what I'm talking about.

First and foremost, I read the first of the sequel series thinking it was "Tokyo Ghoul". Which probably explains whilst I was confused.

The story was engaging, action packed and provided a really different reading experience for me. I'll definitely be picking up more in the series.

My main complaint is that I was royally confused a lot of the time. I had to read panels many a time to figure out what went on. This is all on me and there's definitely some unwritten rules that I haven't figured out. Also would have helped if I didn't start with a sequel series...

** Tags

No tags.


** Links

