#+title: Starfish
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Starfish --- Peter Watts

** Rating

4.5/5 ★★★★½

** Review

Although I had to use up most of my tags for content warnings, the warned content is rarely explicitly described as most of it happened in the character's past. Nonetheless, it is discussed and dramaticly effects the characters in the present.

This was an absolutely gripping book from start to finish and I thoroughly look forward to reading the sequel. The author utilises their PhD in marine biology and extensive research to create a truly immersive deep sea world with strong characters and a gripping plot.

My only criticism, is that the author could have been more descriptive. This is a personal preference but I like to know explicitly what is happening between characters and what is happening in the scenery. The former was somewhat detailed with inner monologues but could have been more unequivocal.

Overall, this is a book that I will likely return to, in spite of not being a sci-fi reader, and will gladly devour the series.

** Links

