#+title: Surprisingly Down to Earth, and Very Funny: My Autobiography
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Surprisingly Down to Earth, and Very Funny: My Autobiography --- Limmy

** Rating

5.0/5 ★★★★★

** Review

Some of the bad reviews of this book are due to the expectation of this being a funny book. Sort of a Christmas stocking filler by Michael MacIntyre. This is not what this book is.

The depth of emotion and unfiltered honesty is unparallelled. Limmy lays everything down on the pages and asks for nothing in return. There is no hidden agenda of justification, redemption or awe. This book is simply says "This is me. Limmy". 

I'm a big fan of Limmy's show and it was lovely hearing the stories behind the sketches but this book was so much more than that. It was one of the most honest books I've ever read. Moreover, there are parts of the book where Limmy talks about his life and I almost was shouting "Yes!" at the book, like I've found someone who gets aspects of my life that no one else will in the same way.

It won't be to everyone's taste but it was definitely my muffet of tea.

** Tags

No tags.


** Links

