#+title: Scorpion Swamp (Fighting Fantasy #8)
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Scorpion Swamp (Fighting Fantasy #8) --- Steve Jackson

** Rating

3.5/5 ★★★½☆

** Review

The open world nature in this book was well done albeit at the expense of the plot.

I managed to play through each of the three (good, neutral and evil) quest lines and died on my way home in all but the evil one. I think I'm going to apply the lesson there to my own life. The different quest lines did significantly effect how I interacted with the world and each new play through did feel like a new adventure. The magic system felt a little tacked on but it still made the book more enjoyable.

Overall, the strength and frequency of the enemies felt too much if you threw a bad initial character roll and in there were lots of ways in which your character could die - even outside of battles.

Compared to book 1, this was definitely more difficult and had better gameplay mechanics - although the plot felt underdeveloped.

Ratings:

Plot: 2
Difficulty: 4
Gameplay: 4

** Links

