#+title: Technology and Barbarism
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Technology and Barbarism --- Michel Nieva

** Rating

4.5/5 ★★★★½

** Review

Thank you NetGalley and Astra Publishing House for sending this book for review consideration. All opinions are my own.

This book felt like a high pressured hose to face in terms of information density, and I loved it. Immediately after this review I will find everything Nieva has written in English and invite him over for tea to discuss technology and politics.

Each essay in this collection is thoroughly researched and herein lies my only complaint. Sometimes it felt like the narrative thread was compromised due to the depth of research. That is, I feel there is an art in choosing what not to write.

Having said that, the writing style was funny, thoughtful, insightful, honest and personal whilst retain objectivity. I would recommend to any one who wants to do Brain Day at the gym.

Also a note to the publisher, with scientific notation the indicie should be present in superscript. That is, with the 2 × 10 -6 on page 207 the -6 should be in superscript.

** Tags

No tags.


** Links

