#+title: The Palestine-Israeli Conflict
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* The Palestine-Israeli Conflict --- Dan Cohn-Sherbok

** Rating

4.5/5 ★★★★½

** Review

Listened not read.

It's difficult to separate the review of this book from the conflict between Israel and Palestine but I will try. This is also my first book on the subject so cannot comment on how it compares to others covering the same topic.

The book is very clearly structured comprising of 3 sections - a Jewish perspective, Arab perspective and a question and answer debate between the two scholars.

Both scholars were clearly incredibly knowledgeable of their area and wrote in a clear and descriptive manner. The debate in particular was a very enjoing and helped shed a different light on each of the scholars argument.

My only fault with this book is that I would have liked a larger debate section whereby each scholar could go into more detail in scrutinising the other's argument.

** Tags

No tags.


** Links

