#+title: The Cat Who Taught Zen
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 23:11:04 GMT
#+filetags: :book-review:

* The Cat Who Taught Zen --- James Norbury

** Rating

4.5/5 ★★★★½

** Review

I was initially going to give this book 2 stars. My reasoning being that I've heard all of the stories and lessons before - except this time they're coming from a cat. I couldn't figure out what this book was trying to achieve as it was just a smattering of Zen stories without any deep exploration.

In the last chapter the author explained the purpose of the book. To take existing Zen fables and ideas, and turn them into something more accessible. I then had to rethink what this book is to ask the question "Does it live up to it's full potential?".

The answer I arrived at is mostly. I get that Zen is concept that is, by it's nature, difficult to explain and can only be experienced. The books provides an accessible platform in which to spring board into some of the ideas of Zen - with the key messages spelled out for the reader. Where it falls short, is that it provides the reader with no next steps or tools to dig deeper. No real mention of breath, no mention of key writings and no mention of the little mind big mind.

For this, it misses out on a 5 star rating but has achieved enough to secure a solid 4.25 stars.

** Links

