#+title: The Music Lesson
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* The Music Lesson --- Victor L. Wooten

** Rating

4.5/5 ★★★★½

** Review

This is a very challenging book to rate. One hand Victor completely achieved his goals of emparting lessons of life, music and listening on the reader. On the other, some of the basis of the encounters/lessons felt a little stretched. Like butter over too much bread. The reason why it's hard to rate is, is that downfall intentional? As is typical of lessons in Zen, the student doesn't understand the question until they discovered the answer; so it is difficult to separate what is inconsistent logic from inept learning.

Overall the lessons are really clearly spelled out for the reader (as they should be) whilst leaving plenty of space for further thought.

This book gets particularly interesting when thinking of ALL of the lessons as life lessons rather than a book about music with lessons that apply to life. With this point, I don't agree with the other reviews that you need to be a musician to glean insight from this book and it's one I'll definitely be reading again numerous times.

** Tags

No tags.


** Links

