#+title: Theroux the Keyhole: When the world went weird
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Theroux the Keyhole: When the world went weird --- Louis Theroux

** Rating

2.5/5 ★★½☆☆

** Review

Saved by the epilogue. The book, although well written and interesting, did not paint Louis or his family in a good light. I think I'm yet to read a book by someone exceptional in their field without constantly reading about the sacrifices of those around them. I did however, appreciate the honesty.

Throughout the book Louis seems to only pay lip service to any change, responsibility and reflection. He talks of rising temperatures caused by man made climate change and then flies the family off on holiday (soon after lockdown rules were relaxed), he talks of the death tolls of COVID and then breaks lockdown rules.

I hope the introspection in the epilogue is just the start, and that Louis and his family have managed to find time for each and give back to communities most affected by their privileged life style. Although I'm doubtful.

** Tags

No tags.


** Links

