#+title: The Warlock of Firetop Mountain (Fighting Fantasy #1)
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* The Warlock of Firetop Mountain (Fighting Fantasy #1) --- Steve Jackson

** Rating

3.5/5 ★★★½☆

** Review

I remember reading this as a teen and re-reading was a lovely trip down memory lane.

That aside, the gameplay was very enjoyable. A few battles were so close I was sweating with nerves whilst the plot really encouraged exploration. Took me a few goes to complete the game and the initial character rolls really changed how I played.

The plot could have been more fleshed out and more mechanics (such as magic?) could have been added in. I'm aware this is the first book in the series but nonetheless, these two elements detracted from the immersion.

That being said, I'll definitely read more from this series and this first book will always hold a special place in my heart.

N.B. I'll try and rate future fighting fantasy books in a similar manner to this one. I've scored this one all 3s as a reference score but I feel it reflects the true scores very well.

Plot: 3
Difficulty: 3
Gameplay: 3

** Tags

No tags.


** Links

