#+title: Trade Wars Are Class Wars: How Rising Inequality Distorts the Global Economy and Threatens International Peace
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:48:05 GMT

* Trade Wars Are Class Wars: How Rising Inequality Distorts the Global Economy and Threatens International Peace --- Matthew C. Klein

** Rating

4.5/5 ★★★★½

** Review

This is a difficult book to rate as a lot of it was beyond my grasp. I feel my rating should be taken in the same vain as if I asked a 7 year old to rate my personal budgeting system.
Bottom line is that I will reread this book with pen and paper (or laptop and text editor) in hand to take more home from this book.

Overall really well written and very succinct. When I say succinct, I'm talking about the high information density of the book and not brevity. The book really opened my eyes to global economics and the interlinked nature of global trade. The reason, for me, why this book loses marks is due to the euro, US and east Asia centric nature. I would have liked to have read more about south America, west Asia and the middle east, and Oceania. I don't mind that the book didn't mention Antarctica.

Ultimately the main piece of information that I took home was that trade wars are not wars between countries. Rather they are wars of the rich and the bankers against everyone else. This book is a possible contender for my books that opened my eyes list but I'll need to reread before making that decision.

** Tags

No tags.


** Links

