#+title: Turtles & Tortoises For Dummies
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 23:11:04 GMT
#+filetags: :book-review:

* Turtles & Tortoises For Dummies --- Liz Palika

** Rating

2.5/5 ★★½☆☆

** Review

It is difficult to truly rate this book being a tortoise novice but there were quite a few things that prevented me from giving this book 5 stars.

The book was overly American focused, particularly on climate and units, which made it more of a "Tortoise and Turtles for US Dummies" rather than the actual title.

Sometimes the world turtle or tortoise was used incorrectly in place of the other. Or, if actually used correctly, lacked sufficient explanation for what feels like an out of place sentence.

Some sentences were outright incorrect. I'm looking at you "Most herbivores are tortoises." - the editor really should have caught that one.

There were little to no references!

The last point in particular lead me to believe this book was written with years of practical experience but ultimately limited to dozens, if not hundreds of tortoises in one particular climate, lacking any formal training in research. Practical experience for a book like this is a must but so is utilising academic research and, contrary to popular belief, the latter cannot be accounted for by merely looking stuff up online.

** Links

