#+title: Values Based Organizations
#+author: Alex Drysdale
#+date: <2026-05-31>
#+export_date: Sun, 31 May 2026 22:01:47 GMT

* Values Based Organizations --- Dr. Thomas Epperson

** Rating

1.5/5 ★½☆☆☆

** Review

Thank you NetGalley and Scribe Media for sending this book for review consideration. All opinions are my own.

I'll start by stating that I'm not a CEO or in senior leadership and thus not the books target audience.

This could have just been a company blog post rather than a book. It follows the structure:

- Explain the thing you actually need to know in chapter 1.
- Subsequently breakdown each step (in the N step plan) in its own chapter.
- Within each chapter present an example of an entity where things were going wrong and then they implemented that step of the plan and things went right.
- At the end of each chapter bullet point the stuff you actually need to know.

And it's a format that self-improvement books have tirelessly followed to turn blog posts into books.

To top it off the main principals of the book where taken from another book published in 2003!

Overall, I felt the key messages were really interesting but this short book was far too long for the content.

** Links

