name: Build HTML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_review:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run build.el with Emacs
        run: emacs --batch -l build.el

      - name: Update docs files
        run: |
          git add docs/
          git commit -m "Built site" || echo "No changes to commit"
        

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
